name: Deploy Flask App to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_VM_KEY }}" > ~/.ssh/server_key.pem
        chmod 600 ~/.ssh/server_key.pem

    - name: Clean up existing app on VM
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/server_key.pem azureuser@57.151.104.162 << 'EOF'
          pkill -f decision_tree_regression.py || true
          rm -rf ~/flask-app || true
          mkdir -p ~/flask-app
          rm -f ~/app.tar.gz
        EOF

    - name: Archive code excluding .git and handle file changes
      run: |
        git archive --format=tar.gz --exclude .git -o app.tar.gz HEAD

    - name: Copy code archive to VM
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/server_key.pem app.tar.gz azureuser@57.151.104.162:~/

    - name: Extract archive on VM
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/server_key.pem azureuser@57.151.104.162 << 'EOF'
          tar -xzf ~/app.tar.gz -C ~/flask-app
          rm ~/app.tar.gz
        EOF

    - name: Start Flask app
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/server_key.pem azureuser@57.151.104.162 << 'EOF'
          cd ~/flask-app
          nohup python3 decision_tree_regression.py > app.log 2>&1 &
        EOF
