name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy project files to EC2 (excluding .git and workflows)
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          --exclude='.git' \
          --exclude='.github' \
          ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/flask-app

      - name: Install dependencies & run Flask App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/flask-app
            pip3 install -r requirements.txt
            nohup python3 decision_tree_regression.py > app.log 2>&1 &
          EOF
